{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.audio;

  mkAppRoutingRules =
    categories:
    let
      categoryRules = lib.mapAttrsToList (
        categoryName: categoryConfig:
        let
          binaryRules = map (binary: {
            actions.update-props."node.target" = targetName;
            matches = [ { "application.process.binary" = binary; } ];
          }) categoryConfig.binaries;
          nameRules = map (appName: {
            actions.update-props."node.target" = targetName;
            matches = [ { "application.name" = "~${appName}"; } ];
          }) categoryConfig.appNames;
          targetName = categoryName;

        in
        nameRules ++ binaryRules
      ) categories;

    in
    lib.flatten categoryRules;
  muteAudioInputs = pkgs.writeShellApplication {
    name = "mute-audio-inputs";

    runtimeInputs = [
      pkgs.jq
      pkgs.pipewire
      pkgs.wireplumber
    ];

    text = ''
      for _ in $(seq 1 20); do
        found=0

        while IFS= read -r id; do
          found=1
          wpctl set-mute "$id" 1 || true
        done < <(
          pw-dump Node | jq -r --argjson names '${builtins.toJSON cfg.mutedInputs}' '
            .[]
            | select(.info.props."media.class" == "Audio/Source")
            | select(.info.props."node.name" as $name | $names | index($name))
            | .id
          '
        )

        [ "$found" -eq 1 ] && exit 0
        sleep 0.5
      done
    '';
  };
in
{
  options.audio = {
    enable = lib.mkEnableOption "the custom PipeWire audio configuration";

    input = lib.mkOption {
      type = lib.types.str;
      example = "alsa_input.pci-0000_01_00.1.analog-stereo";
      description = "The name of the hardware source (microphone) device.";
    };

    inputChannels = lib.mkOption {
      type = lib.types.enum [
        "mono"
        "stereo"
      ];

      example = "mono";

      description = ''
        Channel layout of the hardware input (audio.input).

        Mono sources are duplicated to stereo (FL+FR) before mic processing so
        stereo-only plugins and virtual inputs receive signal on both channels.
        Stereo sources are passed through without upmixing.
      '';
    };

    output = lib.mkOption {
      type = lib.types.str;
      example = "alsa_output.pci-0000_00_1f.3.analog-stereo";
      description = "The name of the hardware sink (output) device.";
    };

    mutedInputs = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      example = [ "alsa_input.usb-046d_Brio_100_2602ZBR396W8-02.mono-fallback" ];
      default = [ ];
      description = "Hardware source node names to mute when PipeWire creates them.";
    };

    appCategories = lib.mkOption {
      type = lib.types.attrsOf (
        lib.types.submodule {
          options = {
            appNames = lib.mkOption {
              type = lib.types.listOf lib.types.str;

              example = [
                "Chromium.*"
                "Firefox"
                "LibreWolf"
              ];

              default = [ ];
              description = "List of application names (regex patterns) to match";
            };

            binaries = lib.mkOption {
              type = lib.types.listOf lib.types.str;

              example = [
                "spotify"
                "vlc"
              ];

              default = [ ];
              description = "List of binary names to match";
            };

            limitThreshold = lib.mkOption {
              type = lib.types.float;
              default = -14.0;
              description = "Limiter threshold in dB for this category.";
            };
          };
        }
      );

      description = "Application categories for audio routing and processing";
    };

    fallbackCategory = lib.mkOption {
      type = lib.types.enum (lib.attrNames cfg.appCategories);
      description = "Default category for applications that don't match any specific rules.";
    };

    eq = lib.mkOption {
      type = lib.types.submodule {
        options = {
          enable = lib.mkEnableOption "a parametric equalizer on the main output";

          file = lib.mkOption {
            type = lib.types.str;
            example = "/path/to/parametric-eq.txt";
            description = "Absolute path to parametric EQ settings file generated by AutoEQ";
          };
        };
      };

      example = {
        enable = true;
        file = "/path/to/parametric-eq.txt";
      };

      default = { };
      description = "Equalizer options";
    };

    micProcess = lib.mkOption {
      type = lib.types.submodule {
        options = {
          enable = lib.mkEnableOption "RNNoise-based microphone noise suppression";

          compressor = lib.mkOption {
            type = lib.types.submodule {
              options = {
                attackTime = lib.mkOption {
                  type = lib.types.float;
                  example = 10.6;
                  description = "Attack time (ms)";
                };

                makeupGain = lib.mkOption {
                  type = lib.types.float;
                  example = 5.9;
                  description = "Makeup gain (dB)";
                };

                ratio = lib.mkOption {
                  type = lib.types.float;
                  example = 4.0;
                  description = "Ratio (1:n)";
                };

                releaseTime = lib.mkOption {
                  type = lib.types.int;
                  example = 500;
                  description = "Release time (ms)";
                };

                threshold = lib.mkOption {
                  type = lib.types.float;
                  example = -18.3;
                  description = "Threshold level (dB)";
                };
              };
            };

            description = "Compressor options";
          };

          vadThreshold = lib.mkOption {
            type = lib.types.float;
            example = 75.0;
            default = 50.0;
            description = "Voice Activity Detection (VAD) threshold percentage for RNNoise.";
          };
        };
      };

      description = "Microphone processing options";
    };

  };

  config = lib.mkIf cfg.enable {

    environment.systemPackages = [
      pkgs.qpwgraph
    ];

    security.rtkit.enable = true;

    services = {
      pipewire = {
        alsa.enable = true;
        enable = true;

        extraLadspaPackages = [
          pkgs.ladspaPlugins
        ]
        ++ lib.optional cfg.micProcess.enable pkgs.rnnoise-plugin;

        jack.enable = true;
        pulse.enable = true;
        wireplumber.enable = true;
      };

      pipewire.extraConfig.pipewire."10-processing-and-linking" =
        let
          appChains = lib.mapAttrsToList mkAppChain cfg.appCategories;
          compressorLinks =
            if inputIsMono then
              [
                {
                  input = "compressor:Left input";
                  output = "rnnoise:Output";
                }
                {
                  input = "compressor:Right input";
                  output = "rnnoise:Output";
                }
              ]
            else
              [
                {
                  input = "compressor:Left input";
                  output = "rnnoise:Output (L)";
                }
                {
                  input = "compressor:Right input";
                  output = "rnnoise:Output (R)";
                }
              ];

          inputIsMono = cfg.inputChannels == "mono";
          mainLoopbacks = map mkMainLoopback (lib.attrNames cfg.appCategories);
          micCaptureStreamProps = if inputIsMono then monoStreamProps else stereoStreamProps;
          # Stereo compressor output is already FL/FR; upmix only for direct HW passthrough.
          micFilterPlaybackStreamProps = stereoStreamProps;
          micPassthroughPlaybackStreamProps =
            if inputIsMono then monoToStereoOutputProps else stereoStreamProps;

          micProcessingSetup =
            if cfg.micProcess.enable then
              [
                {
                  name = "libpipewire-module-filter-chain";

                  args = {
                    "capture.props" = {
                      "media.class" = "Audio/Sink";
                      "node.description" = "HW Mic (Raw Input)";
                      "node.name" = "MicRaw";
                    }
                    // micCaptureStreamProps;

                    "filter.graph" = {
                      links = compressorLinks;

                      nodes = [
                        {
                          name = "rnnoise";
                          control."VAD Threshold (%)" = cfg.micProcess.vadThreshold;
                          label = rnnoiseLabel;
                          plugin = "librnnoise_ladspa";
                          type = "ladspa";
                        }
                        {
                          name = "compressor";

                          control = with cfg.micProcess.compressor; {
                            "Attack time (ms)" = attackTime;
                            "Makeup gain (dB)" = makeupGain;
                            "Ratio (1:n)" = ratio;
                            "Release time (ms)" = releaseTime;
                            "Threshold level (dB)" = threshold;
                          };

                          label = "sc4";
                          plugin = "sc4_1882";
                          type = "ladspa";
                        }
                      ];
                    };

                    "playback.props" = {
                      "media.class" = "Audio/Source";
                      "node.description" = "HW Mic (Processed)";
                      "node.name" = "MicProcessed";
                    }
                    // micFilterPlaybackStreamProps;
                  };
                }
                {
                  name = "libpipewire-module-loopback";

                  args = {
                    "capture.props"."node.target" = cfg.input;
                    "node.description" = "HW-Mic ➜ Processing Chain";

                    "playback.props" = {
                      "node.target" = "MicRaw";
                    }
                    // lib.optionalAttrs inputIsMono monoStreamProps;
                  };
                }
              ]
            else
              [
                {
                  name = "libpipewire-module-loopback";

                  args = {
                    "capture.props"."node.target" = cfg.input;
                    "node.description" = "HW-Mic ➜ Passthrough";

                    "playback.props" = {
                      "media.class" = "Audio/Source";
                      "node.description" = "Hardware Mic (Passthrough)";
                      "node.name" = "MicProcessed";
                    }
                    // micPassthroughPlaybackStreamProps;
                  };
                }
              ];

          mkAppChain = categoryName: categoryConfig: {
            name = "libpipewire-module-filter-chain";

            args = {
              "capture.props" = {
                "audio.position" = "FL,FR";
                "media.class" = "Audio/Sink";
                "node.description" = "${categoryName} (Raw)";
                "node.name" = "${categoryName}";
              };

              "filter.graph".nodes = [
                {
                  control = {
                    "Limit (dB)" = categoryConfig.limitThreshold;
                    "Release time (s)" = 0.1;
                  };

                  label = "fastLookaheadLimiter";
                  plugin = "fast_lookahead_limiter_1913";
                  type = "ladspa";
                }
              ];

              "playback.props" = {
                "media.class" = "Audio/Source";
                "node.description" = "${categoryName} (Processed)";
                "node.name" = "${categoryName}Processed";
              };
            };
          };
          mkMainLoopback = name: {
            name = "libpipewire-module-loopback";

            args = {
              "capture.props"."node.target" = "${name}Processed";
              "node.description" = "${name} ➜ Main";
              "playback.props"."node.target" = if cfg.eq.enable then "MainEQ" else cfg.output;
            };
          };
          monoStreamProps = {
            "audio.channels" = 1;
            "audio.position" = "[ MONO ]";
          };
          # Upmix at the processed source output; loopback channelmix is unreliable for MONO→FL/FR.
          monoToStereoOutputProps = {
            "audio.channels" = 2;
            "audio.position" = "FL,FR";
            "channelmix.normalize" = false;
            "channelmix.upmix" = true;
            "channelmix.upmix-method" = "simple";
            "stream.dont-remix" = false;
          };
          rnnoiseLabel = if inputIsMono then "noise_suppressor_mono" else "noise_suppressor_stereo";
          stereoStreamProps = {
            "audio.position" = "FL,FR";
          };

        in
        {
          "context.modules" =
            appChains
            ++ mainLoopbacks
            ++ micProcessingSetup
            ++ [
              {
                name = "libpipewire-module-loopback";

                args = {
                  "capture.props" = {
                    "media.class" = "Audio/Sink";
                    "node.description" = "Virtual Mic Input (Mixer)";
                    "node.name" = "VirtualMicInput";
                  };

                  "node.description" = "Virtual Mic (Source & Mixer)";

                  "playback.props" = {
                    "media.class" = "Audio/Source";
                    "node.description" = "Input: Virtual Microphone";
                    "node.name" = "VirtualMic";
                  };
                };
              }
              {
                name = "libpipewire-module-loopback";

                args = {
                  "capture.props"."node.target" = "MicProcessed";
                  "node.description" = "Processed Mic ➜ Virtual Mic Mixer";
                  "playback.props"."node.target" = "VirtualMicInput";
                };
              }
              (
                if cfg.eq.enable then
                  {
                    name = "libpipewire-module-filter-chain";

                    args = {
                      "capture.props" = {
                        "audio.position" = "FL,FR";
                        "media.class" = "Audio/Sink";
                        "node.description" = "Main Mix (Pre-EQ)";
                        "node.name" = "MainEQ";
                      };

                      "filter.graph".nodes = [
                        {
                          config.filename = cfg.eq.file;
                          label = "param_eq";
                          type = "builtin";
                        }
                      ];

                      "playback.props"."node.target" = cfg.output;
                    };
                  }
                else
                  {
                    name = "libpipewire-module-loopback";

                    args = {
                      "capture.props" = {
                        "audio.position" = "FL,FR";
                        "media.class" = "Audio/Sink";
                        "node.description" = "Main Mix (Passthrough)";
                        "node.name" = "MainEQ";
                      };

                      "playback.props"."node.target" = cfg.output;
                    };
                  }
              )
            ];
        };

      pipewire.extraConfig.pipewire-pulse."99-app-routing"."pulse.rules" = [
        {
          actions.update-props."node.target" = cfg.fallbackCategory;
          matches = [ { "application.name" = "~.*"; } ];
        }
      ]
      ++ (mkAppRoutingRules cfg.appCategories);

      pipewire.wireplumber.extraConfig."99-alsa-rules"."monitor.alsa.rules" = [
        {
          actions.update-props = {
            "api.alsa.disable-tsched" = true;
            "api.alsa.headroom" = 8192;
            "api.alsa.period-num" = 32;
          };

          matches = [ { "node.name" = cfg.output; } ];
        }
        {
          actions.update-props = {
            "api.alsa.disable-tsched" = true;
            "api.alsa.headroom" = 8192;
            "api.alsa.period-num" = 32;
          };

          matches = [ { "node.name" = cfg.input; } ];
        }
      ];
    };

    systemd.user.services.mute-audio-inputs = lib.mkIf (cfg.mutedInputs != [ ]) {
      description = "Mute configured PipeWire audio inputs";

      after = [
        "pipewire.service"
        "wireplumber.service"
      ];

      wants = [ "wireplumber.service" ];
      wantedBy = [ "default.target" ];

      serviceConfig = {
        Type = "oneshot";
        ExecStart = lib.getExe muteAudioInputs;
      };
    };
  };
}
